#include "Arduino.h"

#if defined(ch551) || defined(ch552)
void digitalwritehighdirectlut(uint8_t pin) {
  //'dpl' (lsb),'dph','b' & 'acc'
  pin;
  // clang-format off
  __asm__(
    ";setb and return are 2 bytes, mul by 3       \n"
    "    mov a,dpl                                \n"
    "    add a,dpl                                \n"
    "    add a,dpl                                \n"
    "    mov dptr,#direct_write_high_lut$         \n"
    "    jmp @a+dptr                              \n"

    "direct_write_high_lut$:                      \n"
    ";no port0                                    \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    
    ";port1                                       \n"
    "    setb _p1_0                               \n"
    "    ret                                      \n"
    "    setb _p1_1                               \n"
    "    ret                                      \n"
    "    setb _p1_2                               \n"
    "    ret                                      \n"
    "    setb _p1_3                               \n"
    "    ret                                      \n"
    "    setb _p1_4                               \n"
    "    ret                                      \n"
    "    setb _p1_5                               \n"
    "    ret                                      \n"
    "    setb _p1_6                               \n"
    "    ret                                      \n"
    "    setb _p1_7                               \n"
    "    ret                                      \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    
    ";no port2                                    \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"

    ";port3                                       \n"
    "    setb _p3_0                               \n"
    "    ret                                      \n"
    "    setb _p3_1                               \n"
    "    ret                                      \n"
    "    setb _p3_2                               \n"
    "    ret                                      \n"
    "    setb _p3_3                               \n"
    "    ret                                      \n"
    "    setb _p3_4                               \n"
    "    ret                                      \n"
    "    setb _p3_5                               \n"
    "    ret                                      \n"
    "    setb _p3_6                               \n"
    "    ret                                      \n"
    "    setb _p3_7                               \n"
    "    ret                                      \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"    
  );
  // clang-format on
}

void digitalwritelowdirectlut(uint8_t pin) {
  //'dpl' (lsb),'dph','b' & 'acc'
  pin;
  // clang-format off
  __asm__(
    ";clr and return are 2 bytes, mul by 3        \n"
    "    mov a,dpl                                \n"
    "    add a,dpl                                \n"
    "    add a,dpl                                \n"
    "    mov dptr,#direct_write_low_lut$          \n"
    "    jmp @a+dptr                              \n"

    "direct_write_low_lut$:                        \n"
    ";no port0                                    \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    
    ";port1                                       \n"
    "    clr _p1_0                                \n"
    "    ret                                      \n"
    "    clr _p1_1                                \n"
    "    ret                                      \n"
    "    clr _p1_2                                \n"
    "    ret                                      \n"
    "    clr _p1_3                                \n"
    "    ret                                      \n"
    "    clr _p1_4                                \n"
    "    ret                                      \n"
    "    clr _p1_5                                \n"
    "    ret                                      \n"
    "    clr _p1_6                                \n"
    "    ret                                      \n"
    "    clr _p1_7                                \n"
    "    ret                                      \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    
    ";no port2                                    \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"

    ";port3                                       \n"
    "    clr _p3_0                                \n"
    "    ret                                      \n"
    "    clr _p3_1                                \n"
    "    ret                                      \n"
    "    clr _p3_2                                \n"
    "    ret                                      \n"
    "    clr _p3_3                                \n"
    "    ret                                      \n"
    "    clr _p3_4                                \n"
    "    ret                                      \n"
    "    clr _p3_5                                \n"
    "    ret                                      \n"
    "    clr _p3_6                                \n"
    "    ret                                      \n"
    "    clr _p3_7                                \n"
    "    ret                                      \n"
    "    nop \n nop \n ret                        \n"
    "    nop \n nop \n ret                        \n"    
  );
  // clang-format on
}
#endif